# Wybierz obraz bazowy dla Node.js 14
FROM node:14

# Ustaw katalog roboczy
WORKDIR /app

# Instaluj zależności
COPY package.json package-lock.json ./
RUN npm install

# Kopiuj pliki do kontenera
COPY . ./

# Uruchom aplikację React
CMD ["npm", "start"]

