version: '3'
services:
  backend:
    build:
      context: ./backend/projects-manager-spring-api
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zajavka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

