version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_manager
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: ./docker
    command: gunicorn project-manager.src:main --bind 0.0.0.0:8080
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/project_manager

volumes:
  db-data:
