version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zajavka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend/projects-manager-spring-api
      dockerfile: Dockerfile.backend
    ports:
      - "8089:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zajavka
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      REACT_APP_BACKEND_SERVER: backend:8080
    ports:
      - "3030:3000"
    depends_on:
      - backend

